### ISSUE TITLE
Import of Combinatorial SBOL with Hierarchical Ordering

### ISSUE THREAD

**Issue by nroehner** [CIDARLAB/knox#9]
Importing the attached file (hierarchical_ordering.xml) on the combinatorial_sbol branch produces the design space pictured in hierarchical_ordering.png, when it should produce the design space pictured in hierarchical_ordering_fixed.png.
[hierarchical_ordering.zip](https://github.com/CIDARLAB/knox/files/2932219/hierarchical_ordering.zip)

**Comment by dany-fu** [comment]
Fixed in latest commit by adding a check for variants in a VariableComponent 

If an SBOL is missing variants in a variable component, would you rather that Knox renders an empty edge or no? 

For example `cds then terminator` and the user forgets to include the variants for terminator, would you rather that it looks like
![screen shot 2019-03-07 at 11 53 33 am](https://user-images.githubusercontent.com/7750862/53973950-b2949280-40cf-11e9-8b85-3246103d5b1f.png)


or be rendered without the blank edge?

**Comment by nroehner** [comment]
I think it would be best if we rendered without the blank edge if possible.

**Comment by dany-fu** [comment]
I agree, and that's how it's shown in the latest commit, so I will leave it that way.
